require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - test_prof/rubocop
  - ./lib/rubocop/cop/lint_env

AllCops:
  TargetRubyVersion: 3.0.1
  NewCops: disable
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "db/migrate/*"
    - "docker/*"
    - "vendor/**/*"
    - 'app/services/**/*'
    - "**/spec/*_helper.rb"
    - config/environments/development.rb

# https://github.com/evilmartians/terraforming-rails/tree/master/tools/lint_env
Lint/Env:
  Enabled: true
  Include:
    - "**/*.rb"
  Exclude:
    - "**/config/environments/**/*"
    - "**/config/application.rb"
    - "**/config/environment.rb"
    - "**/config/puma.rb"
    - "**/config/boot.rb"
    - config/deploy.rb
    - config/deploy/**/*
    - "**/spec/*_helper.rb"
    - "**/spec/**/support/**/*"
    - "lib/generators/**/*"
    - run.rb
    - config/routes.rb
    - config/initializers/backtrace_silencers.rb

Metrics/BlockLength:
  IgnoredMethods:
    [
        "describe",
        "context",
        "FactoryBot.define",
        "configure",
        "factory",
        "specify",
    ]
  Exclude:
    - "config/routes.rb"
    - "spec/**/*"

RSpec/ExampleLength:
  Max: 21

RSpec/EmptyExampleGroup:
  Exclude:
    - "spec/requests/**/*"

# do not require class documentation
Style/Documentation:
  Enabled: false

# ignore comments when calculating method length
Metrics/MethodLength:
  CountComments: false
  Max: 20

# allow accents and ascii in comments
Style/AsciiComments:
  Enabled: false

# ignore comments when calculating line length
Layout/LineLength:
  IgnoredPatterns: [ '(\A|\s)#' ]

# allow free Gemfile organization
Bundler/OrderedGems:
  Enabled: false

# enforce using numeric status codes in http responses
Rails/HttpStatus:
  EnforcedStyle: numeric

# allow more expectations per it
RSpec/MultipleExpectations:
  Max: 5
